name: build

on:
    push:
        branches:
            - ws

jobs:
    build-and-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Build and build
              uses: jeoy/github-deploy-actions@v1.0.1
              env:
                  COMMIT_EMAIL: tritranduc11@gmail.com
                  COMMIT_NAME: test
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BASE_BRANCH: ws
                  DEPLOY_BRANCH: ws-build-js
                  BUILD_SCRIPT: yarn && yarn build
                  FOLDER: dist